Create app
lallamilagro/my_spain pull request #1
Opened 2018-01-14 14:41 UTC by lallamilagro

2018-01-14 14:47 UTC, sivakov512 requested changes

2018-01-14 14:47 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +SECRET_KEY = '+08b&dx2z6+3kw+d9k#z0dsyw!whub40&5_3ywn!%+k8-1brex'
Нельзя такое хранить в репозитории.
Почитай [вот это](https://medium.com/cryptomaniac512/how-to-store-project-settings-in-env-variables-197c7c437b6), а в конце статьи есть ссылка на нужный тебе проект

2018-01-14 14:47 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +DEBUG = True
В проде тебе будет важно переключить это в `False`, так что тоже выноси в переменные окружения

2018-01-14 14:47 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +DATABASES = {
Это тоже выноси в переменные окружения, потому что локально - скулайт, а на проде будет что-то другое.
В либе, которую я упомянул ранее, фича уже включена. Про нее есть пример [тут](https://django-environ.readthedocs.io/en/latest/).

2018-01-20 15:11 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +SECRET_KEY = '+08b&dx2z6+3kw+d9k#z0dsyw!whub40&5_3ywn!%+k8-1brex'
```python
import environ

env = environ.Env()
environ.Env.read_env()
SECRET_KEY = env('SECRET_KEY')
```

2018-01-21 13:56 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +env=environ.Env(
Поставь себе flake8, чтобы он бил по рукам за такое. (в данном случае вокруг `=` должны быть пробелы)

2018-01-21 13:56 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +    'extra': env.db('SQLITE_URL', default='sqlite:////tmp/my-tmp-sqlite.db')
А зачем `extra`?

2018-01-21 13:56 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +import environ
А `DEBUG` не нужно выгружать из окружения?

2018-01-21 14:01 UTC, lallamilagro commented on ms/ms/settings.py
> +    'extra': env.db('SQLITE_URL', default='sqlite:////tmp/my-tmp-sqlite.db')
пример вдохновил (

2018-01-21 14:02 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +    'extra': env.db('SQLITE_URL', default='sqlite:////tmp/my-tmp-sqlite.db')
Я думаю, что тебе не нужно две базы данных.

2018-01-21 14:03 UTC, lallamilagro commented
На самом деле выгрузила на суд код что есть, в работе же проблема с сикрет кей. Сервер не запускается, просит задать сикрет кей. Хотя и не думала что с ним будут проблемы. В примере, что касательно него, так все ясно и лаконично.

2018-01-21 14:04 UTC, cryptomaniac512 commented
Ну так ты запили себе `.env` и напишу там какой-нибудь сикрет кей

2018-01-21 14:06 UTC, lallamilagro commented on ms/ms/settings.py
> +    'extra': env.db('SQLITE_URL', default='sqlite:////tmp/my-tmp-sqlite.db')
ок, соглашусь

2018-01-21 14:13 UTC, lallamilagro commented
![2018-01-22 00-08-20](https://user-images.githubusercontent.com/31769725/35195029-fc42629a-ff08-11e7-95aa-0ba6d95463f4.png)

2018-01-21 14:23 UTC, cryptomaniac512 commented
Объявление переменных окружения делается без пробелов.
`SECRET_KEY=lolkekcheburek`

2018-01-23 14:06 UTC, lallamilagro commented
![2018-01-23 23-55-20](https://user-images.githubusercontent.com/31769725/35279990-79c7a81e-009a-11e8-90b6-e0a9df80a700.png)

2018-01-26 01:37 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +TEMPLATE_DEBUG = DEBUG
`TEMPLATE_DEBUG` упразднен с версии 1.8

2018-01-26 01:37 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +    'default': env.db(),
Покажи как в своем `.env` ты объявила базу данных

2018-01-26 02:45 UTC, lallamilagro commented on ms/ms/settings.py
> +TEMPLATE_DEBUG = DEBUG
ok

2018-01-26 13:03 UTC, lallamilagro commented on ms/ms/settings.py
> +    'default': env.db(),
![2018-01-26 23-01-45](https://user-images.githubusercontent.com/31769725/35440874-108e0af0-02ed-11e8-955c-39507b756d76.png)

2018-01-27 06:56 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +    'default': env.db(),
Зачем этот `DATABASES`?

2018-01-27 13:58 UTC, lallamilagro commented on ms/ms/settings.py
> +    'default': env.db(),
по аналогии с примером в документации. вообще, как я поняла, то что выносится в переменные окружения, содержит значение в самом этом окружении, т.е. в файле .env. А в общедоступных файлах нужно только сослаться на  .env

2018-01-27 14:03 UTC, cryptomaniac512 commented on ms/ms/settings.py
> +    'default': env.db(),
Во-первых, переменная окружения по умолчанию строка. Твой словарь не будет работать, потому что в переменных окружения не существует структур.
Во-вторых, если ты внимательно читала доки, то могла заметить, что для объявления бд используется `DATABASE_URL` и никаких иных переменных для этого не нужно.

2018-01-27 14:07 UTC, lallamilagro commented on ms/ms/settings.py
> +    'default': env.db(),
да, заметила, исправлю

2018-01-27 14:08 UTC, sivakov512 approved these changes

2018-01-27 14:23 UTC, merged