Application development - history
lallamilagro/my_spain pull request #5
Opened 2018-05-05 15:41 UTC by lallamilagro

2018-05-05 16:19 UTC, lallamilagro commented
@sivakov512 
![2018-05-06 01-51-29](https://user-images.githubusercontent.com/31769725/39665157-109d4644-50d3-11e8-80c1-cd224b8b0090.png)
Не фиксируется гитигнор с изменениями. В какую сторону копать для решения? _(нашла только похожую проблему с папками, в которой решением является изучение субмодулей. но это же не мой случай..)_

2018-05-10 14:44 UTC, lallamilagro commented
@sivakov512 
![2018-05-11 00-30-34](https://user-images.githubusercontent.com/31769725/39875386-df2eb856-54b3-11e8-842c-dd9c87627627.png)

Может быть не лучшее творение, но пыталась практиковаться и экспериментировать. На скрине не видно курсора. В списке подчеркнута якорная ссылка на заголовок в тексте. Кроме того, некоторое форматирование внешнего вида текста, изображение в тексте, фон без прокручивания. Тесты проходят.

2018-05-11 13:24 UTC, sivakov512 commented on .gitignore
> +*.sqlite3
У тебя тут в гитигноре куча всякого мусора, который у тебя в проекте никогда не появится.
Перечисли здесь, пожалуйста, только то, что нужно.

2018-05-11 13:24 UTC, sivakov512 commented on ms/historia/admin.py
> +from django.contrib import admin
Модуль пустой и не нужен. Зачем он здесь?

2018-05-11 13:24 UTC, sivakov512 commented on ms/historia/models.py
> +from django.db import models
Аналогично. Модуль пустой и не используется.

2018-05-11 13:24 UTC, sivakov512 commented on ms/ms/settings.py
> +    'historia',
Вообще, смешивать языки в проекте - плохо. Код ты пишешь на ангельском, на нём же и пиши имена.

2018-05-11 13:24 UTC, sivakov512 commented on ms/templates/header.html
> +    <h1><a href="http://127.0.0.1:8000/">Sigue tu sueño</a></h1>
И что, на сайте будет ссылка на локалхост? Почитай, как правильно делать ссылки в джанго шаблонах. А ещё здесь можно было сделать просто `"/"`.

2018-05-11 13:34 UTC, lallamilagro commented on ms/historia/admin.py
> +from django.contrib import admin
было создано по умолчанию. исправила.

2018-05-13 13:41 UTC, sivakov512 requested changes

2018-05-13 13:41 UTC, sivakov512 commented on ms/history/admin.py
> +
Пустой ненужный модуль.

Пожалуйста, проверяй код за собой, чтобы это не делал я - после прошлого ревью можно было проверить все модули и убрать лишние.

2018-05-13 13:41 UTC, sivakov512 commented on ms/history/models.py
> +
Опять пустой модуль. Почему не удален? Для кого я замечания писал?

2018-05-13 13:41 UTC, sivakov512 commented on ms/templates/header.html
> +      <a href = "/history/">Historia</a>
Когда я говорил разобраться как в джанге правильно работать с урлами в шаблонах, я надеялся, что ты почитаешь это https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#url

Почему то, как это сделано сейчас - плохо?
Потому что если ты решишь поменять какой-то урл в паттернах, то нихуя работать не будет - здесь то ты его не изменила. Если у тебя будет много раз использоваться один урл, то при каждом изменении тебе предстоит искать его по всему проекту и менять.

2018-05-13 13:41 UTC, sivakov512 commented on ms/templates/header.html
> +      <a href = "/articulos/">Artículos</a>
И куда эти ссылки сейчас ведут?
Полагаю никуда. Тогда нафига писать то, что еще не работает?
Если тебе эти ссылки важны для интерфейса, то поставь вместо урла `"#"`.

2018-05-13 13:41 UTC, sivakov512 commented on ms/templates/page/history.html
> +{% block content %}
Ты расширяешь блок `content` у шаблона `base.html`, значит здесь должно быть включаемое тело страницы, если только `base.html` не пустой ненужный файл.
А у тебя здесь доктайп, хедэр и тело, которые ты включишь в тело. Получается невалидное гавно.

2018-05-13 13:41 UTC, sivakov512 commented on ms/history/views.py
> +
Лишние переносы строки в конце модуля - нарушение PEP

2018-05-13 13:41 UTC, sivakov512 commented on ms/history/views.py
> +
Вообще поставь себе flake8 и сделай, чтобы vscode ругался за стилистические ошибки, чтобы делать хорошо.

2018-05-13 13:41 UTC, sivakov512 commented on ms/templates/header.html
> +      <a href = "/history/">Historia</a>
Даже в начальном туторе это было https://docs.djangoproject.com/en/2.0/intro/tutorial03/#namespacing-url-names

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  .Python
Зачем тебе это?
На строку ниже это тоже распространяется.

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  eggs/
А это тебе зачем? Ты пакеты в PyPi собираешься делать?
На строку ниже это тоже распространяется.

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  *.egg-info/
Аналогично

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  *.egg
Аналогично

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  venv/
Оооочень много енвов у тебя тут конечно

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  *.db
Вроде ниже есть какая-то бд, зачем эта? У тебя две базы данных?

2018-05-13 13:41 UTC, sivakov512 commented on .gitignore
>  /.pytest_cache
Не видел пайтеста в проекте. Зачем это?

2018-05-22 12:05 UTC, lallamilagro commented on ms/templates/page/history.html
> +{% block content %}
а что в этом шаблоне нужно оставить то? у меня в нем хэад и боди, в котором и заключен контент

2018-05-22 12:48 UTC, sivakov512 commented on ms/templates/page/history.html
> +{% block content %}
Подумай хоршенько.
Ты внутрь блока `content` засовываешь `<html><head>...</head>...</html>`

2018-05-22 12:48 UTC, sivakov512 commented on ms/templates/page/history.html
> +{% block content %}
При том, что в base у тебя наверняка уже есть базовая структура страницы. Фактически, ты засовываешь страницу в страницу, а не контент в страницу.

2018-05-22 12:49 UTC, lallamilagro commented on ms/templates/page/history.html
> +{% block content %}
по смыслу нужно только содержимое <body> </body>, но разве можно так разрывать хтмл-документ?

2018-05-22 12:52 UTC, sivakov512 commented on ms/templates/page/history.html
> +{% block content %}
Всм разрывать?

У тебя есть базовый шаблон, например
```html
<html>
<head>
<title>Жопа слона</title>
</head>

<body>
<блок контента, который будем расширять>
</body>
```

Логично, что внутри body должно встраиваться содержиоме для тела. Ты же сейчас встраиваешь структуру целой страницы внутрь тела базовой страницы (в ее блок контента).

2018-05-22 12:55 UTC, sivakov512 commented on ms/templates/page/history.html
> +{% block content %}
Вот, почитай, пожалуйста
https://docs.djangoproject.com/en/2.0/ref/templates/language/#template-inheritance

2018-06-08 01:53 UTC, lallamilagro commented
@sivakov512

2018-06-11 09:23 UTC, sivakov512 approved these changes
Все выглядит хорошо, кроме двух небольших замечаний.

2018-06-11 09:23 UTC, sivakov512 commented on .gitignore
> +*.pyc
Выше уже есть `*.py[cod]`, в него и это выражение должно входить.

2018-06-11 09:23 UTC, sivakov512 commented on ms/history/views.py
> +
Насколько я вижу, `flake8` ты так и не поставила.

2018-06-14 23:49 UTC, lallamilagro commented
@sivakov512

2018-06-14 23:51 UTC, sivakov512 approved these changes

2018-06-21 12:28 UTC, merged